#runtime: go113
runtime: go111
main: ./cmd/web
handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  FIREBASE_API_KEY: ""
  FIREBASE_AUTH_DOMAIN: ""
  FIREBASE_DB_URL: ""
  FIREBASE_PROJECT_ID: ""
  FIREBASE_STORAGE_BUCKET: ""
  FIREBASE_MESSAGING_SENDER_ID: ""
  FIREBASE_APP_ID: ""
  FIREBASE_MEASUREMENT_ID: ""
